engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: false
ratings:
  paths:
  - index.js
  - lib/utils.js
  - lib/plugins/**
exclude_paths:
- test.js
